name: shopsense_new
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

  # Các package bạn đang dùng trong project
  http: ^1.2.2
  shared_preferences: ^2.2.3
  provider: ^6.1.1
  intl: ^0.19.0
  file_picker: ^8.0.0
  google_nav_bar: ^5.0.6
  url_launcher: ^6.1.10
  uni_links: ^0.5.1
#  webview_flutter: ^4.4.1
  flutter_inappwebview: ^5.8.0
  webview_flutter: ^4.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
