name: shopsense_new
description: Multi vendor ecommerce website
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_nav_bar: ^5.0.6
  http: ^1.1.0
  provider: ^6.0.5
  shared_preferences: ^2.2.1
  file_picker: 6.1.1
  webview_flutter: ^4.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  intl: ^0.19.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
